package com.zbh.jvm.hotspot.src.share.vm.utilities;

public class BasicType {

    public static final int JVM_ACC_PUBLIC = 0x0001;/* visible to everyone */
    public static final int JVM_ACC_PRIVATE = 0x0002;  /* visible only to the defining class */
    public static final int JVM_ACC_PROTECTED = 0x0004; /* visible to subclasses */
    public static final int JVM_ACC_STATIC = 0x0008;/* instance variable is static */
    public static final int JVM_ACC_FINAL = 0x0010; /* no further subclassing, overriding */
    public static final int JVM_ACC_SYNCHRONIZED = 0x0020; /* wrap method call in monitor lock */
    public static final int JVM_ACC_SUPER = 0x0020; /* funky handling of invokespecial */
    public static final int JVM_ACC_VOLATILE = 0x0040;/* can not cache in registers */
    public static final int JVM_ACC_BRIDGE = 0x0040; /* bridge method generated by compiler */
    public static final int JVM_ACC_TRANSIENT = 0x0080; /* not persistent */
    public static final int JVM_ACC_VARARGS = 0x0080; /* method declared with variable number of args */
    public static final int JVM_ACC_NATIVE = 0x0100; /* implemented in C */
    public static final int JVM_ACC_INTERFACE = 0x0200; /* class is an interface */
    public static final int JVM_ACC_ABSTRACT = 0x0400; /* no definition provided */
    public static final int JVM_ACC_STRICT = 0x0800; /* strict floating point */
    public static final int JVM_ACC_SYNTHETIC = 0x1000; /* compiler-generated class, method or field */
    public static final int JVM_ACC_ANNOTATION = 0x2000; /* annotation type */
    public static final int JVM_ACC_ENUM = 0x4000; /* field is declared as element of enum */


    public static final int T_BOOLEAN = 4;
    public static final int T_CHAR = 5;
    public static final int T_FLOAT = 6;
    public static final int T_DOUBLE = 7;
    public static final int T_BYTE = 8;
    public static final int T_SHORT = 9;
    public static final int T_INT = 10;
    public static final int T_LONG = 11;
    public static final int T_OBJECT = 12;
    public static final int T_ARRAY = 13;
    public static final int T_VOID = 14;
    public static final int T_ADDRESS = 15;
    public static final int T_NARROWOOP = 16;
    public static final int T_METADATA = 17;
    public static final int T_NARROWKLASS = 18;
    public static final int T_CONFLICT = 19;        // for stack value type with conflicting contents
    public static final int T_ILLEGAL = 99;
    public static final int T_Throwable = 100;


    public static final int JVM_SIGNATURE_ARRAY = '[';
    public static final int JVM_SIGNATURE_BYTE = 'B';
    public static final int JVM_SIGNATURE_CHAR = 'C';
    public static final int JVM_SIGNATURE_CLASS = 'L';
    public static final int JVM_SIGNATURE_ENDCLASS = ';';
    public static final int JVM_SIGNATURE_ENUM = 'E';
    public static final int JVM_SIGNATURE_FLOAT = 'F';
    public static final int JVM_SIGNATURE_DOUBLE = 'D';
    public static final int JVM_SIGNATURE_FUNC = '(';
    public static final int JVM_SIGNATURE_ENDFUNC = ')';
    public static final int JVM_SIGNATURE_INT = 'I';
    public static final int JVM_SIGNATURE_LONG = 'J';
    public static final int JVM_SIGNATURE_SHORT = 'S';
    public static final int JVM_SIGNATURE_VOID = 'V';
    public static final int JVM_SIGNATURE_BOOLEAN = 'Z';

}
